### ISSUE TITLE
플랜 수정/삭제

### ISSUE THREAD

**Issue by wonyongChoi05** [haruharulab/Adapfit-Backend#21]
플랜 수정/삭제는 모든 관리자 권한을 가진 유저가 접근할 수 있으므로 자신이 작성한 플랜에 대해서만 수정/삭제가 가능하도록 한다.

**Comment by leehj050211** [comment]
그러면 관리자 계정을 삭제할 시 자신이 만든 플랜은 어떻게 되나요?

**Comment by wonyongChoi05** [comment]
영속성 전이는 하지 않도록 하겠습니다.
